- name: filters Demo
  hosts: localhost
  connections: local
  vars:
    x: 1,2,3
    tasks:
      - name: Print first value of csv - x
        ansible.builtin.debug:
          msg: "{{ x | split (',')[1] }}"
          vars:
            split: "{{ x | split (',')}}"
