- name: Error Handling
  hosts: localhost
  connections: local
  tasks:
    - name: Fail this command
      ansible.builtin.shell: exit1
      ignore_error: true

    - name: Print Hello
      ansible.builtin.debug:
        msg: Hello
